### ISSUE TITLE
the config don't accept data

### ISSUE THREAD

**Issue by andrea26690** [andrea-mattioli/bticino_X8000_rest_api#1]
hi, when i try to 
2.2. Update your config.yml 
the configurator return me 

Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'client_id': xxxxxxx
if i try to insert only one too : 
Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'client_id': 1} (i try 1 value for example)

how can i fix to insert the values recived by mail?

**Comment by andrea-mattioli** [comment]
Hi Andrea, don't use special characters on api_user like "@".
I added api authentication to protect add-on there aren't login on legrand
but only for api-add on.
you can chose for example:
api_user: bticino
api_pass: 'hard password'
this is only for web protection!
hope to helped you!


Il giorno mer 22 apr 2020 alle 17:47 andrea26690 <notifications@github.com>
ha scritto:

**Comment by andrea26690** [comment]
i've correctly configured the config.yml
but when i Allow app permissions, the browser show me an error.
i think that is wrong the legrand app configuration (request and response URL)
i've configured my homeass with an https://xxx.duckdns.org (and the internal port is 8123 forward on the 443 wan port)
and the 5588 is open on the local ip

when i go on http://my_hassio_ip:5588/rest i see only " [] "

how can i fix?, what the correct url?

can u contact me by mail? i'm from italy

thanks

**Comment by andrea-mattioli** [comment]
Hi Andrea, i think you have an ssl issue, see this thred
https://community.home-assistant.io/t/bticino-smarther-x8000/158468/11




*Andrea MattioliRed Hat Certified Engineer*
Rhel Consultant
________________________
Mob +39.328/1452201
[image: LinkedIn Andrea Mattioli] <http://it.linkedin.com/in/amattioli2>

**** Riservatezza / Confidentiality ****
In ottemperanza al D.L. n. 196 del 30/6/2003 in materia di protezione dei
dati personali, le informazioni contenute in questo messaggio sono
strettamente riservate ed esclusivamente indirizzate al destinatario
indicato (oppure alla persona responsabile di rimetterlo al destinatario).
Vogliate tener presente che qualsiasi uso, riproduzione o divulgazione di
questo messaggio è vietato. Nel caso in cui aveste ricevuto questo
messaggio per errore, vogliate cortesemente avvertire il mittente e
distruggere il presente messaggio.

According to Italian law D.L. 196/2003 concerning privacy, if you are not
the addressee (or responsible for delivery of the message to such person)
you are hereby notified that any disclosure, reproduction, distribution or
other dissemination or use of this communication is strictly prohibited. If
you have received this message in error, please destroy it and notify us by
email.


Il giorno gio 23 apr 2020 alle ore 17:48 andrea26690 <
notifications@github.com> ha scritto:

**Comment by andrea-mattioli** [comment]
Hi Andrea you solve your issue?

**Comment by andrea-mattioli** [comment]
Solved on 0.3 version
