### ISSUE TITLE
Integration failed to start

### ISSUE THREAD

**Issue by Tinwelint78** [andrea-mattioli/bticino_X8000_rest_api#4]
I had a working setup, with two x8000 thermostats and a raspberry with hassio and home assistant installed.
Yesterday the x8000 integration has stopped abruptly to work. I have tried many reboots and also a rebuild, but it won't start anymore. The log reports some errors:

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> 2020/07/14 06:23:33 [notice] 268#268: using the "epoll" event method
> 2020/07/14 06:23:33 [notice] 268#268: nginx/1.18.0
> 2020/07/14 06:23:33 [notice] 268#268: OS: Linux 4.19.127-v7l
> 2020/07/14 06:23:33 [notice] 268#268: getrlimit(RLIMIT_NOFILE): 1048576:1048576
> 2020/07/14 06:23:33 [notice] 268#268: start worker processes
> 2020/07/14 06:23:33 [notice] 268#268: start worker process 270
> /ssl/fullchain.pem /ssl/privkey.pem
> [06:23:33] INFO: certificate found!
> 2020/07/14 06:23:33 [notice] 268#268: signal 15 (SIGTERM) received from 184, exiting
> 2020/07/14 06:23:33 [notice] 270#270: exiting
> 2020/07/14 06:23:33 [notice] 270#270: exit
> 2020/07/14 06:23:34 [notice] 268#268: signal 14 (SIGALRM) received
> 2020/07/14 06:23:34 [notice] 268#268: signal 17 (SIGCHLD) received from 270
> 2020/07/14 06:23:34 [notice] 268#268: worker process 270 exited with code 0
> 2020/07/14 06:23:34 [notice] 268#268: exit
> [06:23:34] INFO: Setup config file...
> 2020/07/14 06:23:34 [notice] 280#280: using the "epoll" event method
> 2020/07/14 06:23:34 [notice] 280#280: nginx/1.18.0
> 2020/07/14 06:23:34 [notice] 280#280: OS: Linux 4.19.127-v7l
> 2020/07/14 06:23:34 [notice] 280#280: getrlimit(RLIMIT_NOFILE): 1048576:1048576
> 2020/07/14 06:23:34 [notice] 280#280: start worker processes
> 2020/07/14 06:23:34 [notice] 280#280: start worker process 286
> Traceback (most recent call last):
>   File "bticino.py", line 516, in <module>
>     schedule_update_token()
>   File "bticino.py", line 512, in schedule_update_token
>     f_refresh_token()
>   File "bticino.py", line 199, in f_refresh_token
>     if not check_empty_item("refresh_token"):
>   File "bticino.py", line 77, in check_empty_item
>     json_object=get_json()
>   File "bticino.py", line 85, in get_json
>     json_object = json.load(a_file)
>   File "/usr/lib/python3.8/json/__init__.py", line 293, in load
>     return loads(fp.read(),
>   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
>     raise JSONDecodeError("Extra data", s, end)
> json.decoder.JSONDecodeError: Extra data: line 1 column 4011 (char 4010)
> [06:23:37] INFO: Api address: https://xxxxxxxxx.duckdns.org:5588/
> Traceback (most recent call last):
>   File "mqtt.py", line 5, in <module>
>     from bticino import send_thermostat_cmd, load_api_config_arg
>   File "/hassio_bticino_smarter/bticino.py", line 516, in <module>
>     schedule_update_token()
>   File "/hassio_bticino_smarter/bticino.py", line 512, in schedule_update_token
>     f_refresh_token()
>   File "/hassio_bticino_smarter/bticino.py", line 199, in f_refresh_token
>     if not check_empty_item("refresh_token"):
>   File "/hassio_bticino_smarter/bticino.py", line 77, in check_empty_item
>     json_object=get_json()
>   File "/hassio_bticino_smarter/bticino.py", line 85, in get_json
>     json_object = json.load(a_file)
>   File "/usr/lib/python3.8/json/__init__.py", line 293, in load
>     return loads(fp.read(),
>   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
>     raise JSONDecodeError("Extra data", s, end)
> json.decoder.JSONDecodeError: Extra data: line 1 column 4011 (char 4010)
> [cmd] /hassio_bticino_smarter/run.sh exited 1
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-finish] sending all processes the TERM signal.
> 2020/07/14 06:23:39 [notice] 286#286: signal 1 (SIGHUP) received from 325, ignoring
> 2020/07/14 06:23:39 [notice] 280#280: signal 1 (SIGHUP) received from 325, reconfiguring

Is there anything I can do to debug the issue further?

**Comment by andrea-mattioli** [comment]
Hi, try to remove the directory /config/.bticino_smarter and then rebuild the add-on.
After rebuild, you must open the web application and click "get your code" (follow the guide).
Try this solution and tell me the result.

**Comment by Tinwelint78** [comment]
ok, the solution is working! Have I to remove integration configuration directory again on next update or has it became corrupt for some unknown reason?

**Comment by andrea-mattioli** [comment]
i don't know why with this hassio's update generated this issue, but in the most case this is the root way to solve this issue.
